### ISSUE TITLE
improved interface for clicking on the upset plot

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1044]
During the workshop today we discovered it is difficult to select data that has metagenomes AND metaproteomics . The bar chart in the upset plot is too small (n=17) to click on and the faceted search is an OR selection. Can we make the bar + number for each row in the  upset chart clickable

cc @emileyfadrosh

**Comment by aclum** [comment]
To be discussed with kitware but I think the easiest solution would be to also make the numbers links.  @marySalvi @naglepuff please weigh in here.

**Comment by aclum** [comment]
![Screenshot 2024-04-17 at 4 52 02 PM](https://github.com/microbiomedata/nmdc-server/assets/8196591/347d8fd8-77e0-496a-9ac0-a2bd3d3a6a76)
In the screenshot the bar chart with a corresponding number of 33 is the lowest bar chart I can click on.

**Comment by aclum** [comment]
Action is to make how rectangular area, including the number clickable.

**Comment by ssarrafan** [comment]
Discussed at infra sync meeting today.  Alicia would like this issue broken out into two different issues. This specific issue will be for expanding the clickable area of the upset plot to include the numbers and not just the bar chart so that it will be easier to click even if the bar chart is too thin to work.  The second issue will be to allow specifying and/or operator for omics type faceted search. See https://github.com/microbiomedata/nmdc-server/issues/1335

**Comment by ssarrafan** [comment]
@marySalvi do you think you can finish this today before the release?  Or should we move this to the next sprint?

**Comment by marySalvi** [comment]
> @marySalvi do you think you can finish this today before the release? Or should we move this to the next sprint?

@ssarrafan I don't think it would be reviewed in time to be fully completed today. I'll move it to next sprint.

**Comment by aclum** [comment]
looks good on dev!
