### ISSUE TITLE
Study Page review

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#1143]
**Bug**
Fix ASAP
- [x] NEON studies seem to be having trouble with the associations. With each page transition, the list got longer (1min-2:22min) ..  [see this video](https://drive.google.com/file/d/1H9QKQn5ht4gkHRyQRVgdguzFWbDWFlhq/view?usp=drive_linkrl) 
  - 2-3hrs , what's causing it is unknown.
- [x] nmdc:sty-11-db67n062 has NEON soil samples, but it's not part of the NEON soil consortia. Should only be linked to NEON consortia (nmdc:sty-11-nxrz9m96) not associated with (nmdc:sty-11-34xj1150)
  - [x] I think we can fix this with a change sheet? @brynnz22  can you take a look.
  - [x] Brynn will remove nmdc:sty-11-34xj1150 part of association for nmdc:sty-11-db67n062
  - [x] DP ingest still needed but mongo is done
- [x] Something weird is happening with the GROW stud page & its association with the River Corridor SFA [See this vide](https://drive.google.com/file/d/190USOTiAmK5j2_SEJUGFh3umuo4-cKbS/view?usp=sharing)
- [x] Above is also happening with JP's project. (gold:Gs0128850) "[Lab enrichment of tropical soil microbial communities from Luquillo Experimental Forest, Puerto Rico](https://drive.google.com/file/d/1IWQz4Xp8zg-fX87Q9dJrzO9_E5z41v62/view?usp=sharing)" is the name in the acordian, but it's supposed to be "[Microbial Carbon Transformations in Wet Tropical Soils: Effects of Redox Fluctuation](https://drive.google.com/file/d/1dxMMAXs6sTkRUBjpxnuWbjFWfKLhh3XU/view?usp=sharing)". @marySalvi accordion should show "title", not "name" of study_set record
- [x] gold:Gs0114663 : is appearing as a child and as an individual study.
  - I know there was weird-ness with River corridor vs GROW vs WHONDRS. @lamccue Can you look at this and let me know if it's what we were expecting? Did you check in with James? 
  - GROW should be listed as a child of the River Corridor SFA & not listed as a parent project. It's associated with WHONDRS, but it does not need to appear in the accordion.
  - GROW is a child of WHONDRS & that's why it's appearing as a top level study and a child. 
  - Add a "your parent exists here & you're a child of something else" don't show it as a top level study
  - part_of = this child has this parent. 
  - associated study is showing ANY children that name this thing as its `part_of`. 
  - Ideally, GROW appears as a child of River Corridor. In WHONDRS, GROW is associated but it's NOT a child. 
  - In the schema, GROW has part_of WHONDRS. Will update the backend to make it appear as a child. Across the board, studies can be part of a consortia & associated, but aren't children. Child Parent displayed relationships are exclusive to 'common types' ... across types, link as associated in the landing page but don't show it. 
  - ~.5-1 hr
- [x] #1157
- [x] nmdc:sty-11-r2h77870 : massive data DOI is missing[ see original here](https://docs.google.com/presentation/d/1LQ_yQF2IIYqfP1KOlGtpRT3-zwvTiO-_v_4XUwrba2A/edit?usp=sharing) (slide 8) & what it is [on dev now](https://drive.google.com/file/d/1m_7qkV8wKcgPDdkgFICQdq0dNLi4kKKN/view?usp=sharing)
- [x] gold:Gs0135149: There were 2 ESS-Dive links. One was moved to data. Where did the other one go? See [slide 3](https://docs.google.com/presentation/d/1LQ_yQF2IIYqfP1KOlGtpRT3-zwvTiO-_v_4XUwrba2A/edit?usp=sharing)
- [x] nmdc:sty-11-5tgfr349: had 2 ESS Dive links, now they're missing [See slide 7](https://drive.google.com/file/d/1m_7qkV8wKcgPDdkgFICQdq0dNLi4kKKN/view?usp=sharing)
  - Links are still in mongo 
- [x] ~you can no longer get to a study page by clicking anywhere within a study description box, even for studies which don't have children.~
- [x] consortia that have children (NEON) don't show omics types and counts when the tick is expanded
- [x]  issue consortia that have children (NEON) don't show omics types and counts when the tick is expanded. FWIW this is showing up correctly for studies : see https://github.com/microbiomedata/nmdc-server/issues/1143#issuecomment-1955408017 

**Bug: Capitalization**
Small fix / low priority
 - [x] nmdc:sty-11-8xdqsn54: [edi data source](https://drive.google.com/file/d/1j1duc6cuYxC68F93uiUJKnoXPaM1Ennj/view?usp=sharing) should be capitalized
 - [x] gold:Gs0114675 : [jgi data source](https://drive.google.com/file/d/1aOQxIVqgVGNyaRMn7RhVm_G0WP1unEFt/view?usp=sharing) should be capitalized
 - [x] gold:Gs0128850: [jgi data doi](https://drive.google.com/file/d/184gjQzMRLjrD07PcylLM8WLyTtj_uy2b/view?usp=sharing) source not capitalized
- [x] gold:Gs0103573: [data doi JGI](https://drive.google.com/file/d/16yI7ZpPVG70koYB5xIlNmbhWGcNXc88_/view?usp=sharing) not capitalized
- [x] nmdc:sty-11-5tgfr349 : da[ta doi kbase](https://drive.google.com/file/d/1vpGq-Unvb1yIgY8AzjDCGgFNHNDe2Mvi/view?usp=sharing) not capitalized
- [x] gold:Gs0114663 : [jgi not capitalized](https://drive.google.com/file/d/1dSq7ZeRVJh4qof30MSDhEkoJhbRz37RR/view?usp=sharing) in data DOI
- [x] gold:Gs0110138: [jgi not capitalized](https://drive.google.com/file/d/14qxgXFg52U0fxfwJBuv9ZFS0we4lTPN5/view?usp=sharing) in data doi
- [x] #1156

**Improvement / Change**
High Priority
- [x] add Tool tip for **Studies**:  hypothesis-driven experimental data sets ## research driven? i think we discussed hypothesis and decided to avoid that?
- [x] add Tool tip for **Consortia**:  standardized data collections
- [x] reorder: put Consortia first, then Studies
- [x] Remove "omics data coming soon" from parent studies if there's no data .. or show that there's data in the children?
- [x] Make team list collapse & expand. Show 3 lines and hide the rest .. collapsable (it's easier)
- [x] add WHONDRS logo (Lee Ann can share the .jpg file, just needs to know where it goes)
- [x] change icons; suggest these: an individual study -> book; a parent study -> book-multiple-outline; consortia (parent and child) -> database (see slide deck)

**Improvement / Change**
Low Priority, should do some user research, for the next 'refresh'
- [x] nmdc:sty-11-hdd4bf83: Missing PI photo
- [x] nmdc:sty-11-t91cwb40: missing PI photo
- [x] gold:Gs0110119: has a parent project logo instead of PI photo, change for PI photo
- [x] additional images are in this [folder](https://drive.google.com/drive/folders/1fjMlIlZzY_n_5UddsEE2GLs4uyI1tlth)
- [x] Add a collapse / expand all children studies
- [x]  nmdc:sty-11-5tgfr349: Kelly's orcid is listed in links, remove (@brynnz22 )
- [x] gold:Gs0154244: EMP, Janet's ORICD is the only one shared, but we list 3 PIs
- [ ]

**Comment by mslarae13** [comment]
@aclum & @lamccue feel free to edit my comment and add your updates / observations

**Comment by mslarae13** [comment]
Capitalization errors for the Data sets DOI providers should be 1 quick fix

**Comment by mslarae13** [comment]
Missing ESS-Dive and Massive should be a quick fix

**Comment by aclum** [comment]
would like to upvote this item
Remove "omics data coming soon" from parent studies if there's no data .. or show that there's data in the children?
we should also remove the sample count. @emileyfadrosh expressed interest in showing data for the children.

**Comment by aclum** [comment]
image for issue consortia that have children (NEON) don't show omics types and counts when the tick is expanded
![Screenshot 2024-02-20 at 3 53 21 PM](https://github.com/microbiomedata/nmdc-server/assets/8196591/af1b8092-9e8b-4639-a0e7-88864c74db9c)

**Comment by aclum** [comment]
I'm not sure if this was discussed in the study page refresh squad previously but users may care more about studies which have subprojects than what the study_category is. If so, we could have research study vs consortium be tags instead of having them separated. Then you could have all studies which have children at the top, and have them tagged or info on the study page about if the category is a research study vs consortium. If we are going to leave the main page as is we should add a tool tip which displays the value for the schema description for those enumerations.

**Comment by aclum** [comment]
It is not intuitive to me that GROW doesn't show up under WHONDRS in the main page but shows up as being a part of WHONDRS on the individual study page.

**Comment by aclum** [comment]
@mslarae13 for ORCID if you click on someone's name on the team list it will show their ORCID if it is in the schema (has_credit_associations.applies_to_person.orcid)

**Comment by emileyfadrosh** [comment]
I have three main requests for how this is represented on the data portal: 
1. The studies & consortia need to be represented in a more intuitive way. 
- [ ] Splitting them and having the consortia at the bottom is not intuitive. Instead, as Alicia mentioned, these should be merged so that users can clearly see what studies are available and how they are nested. 
- [ ] The consortia need to be ordered so they appear at the top of the page so it's immediately apparent that these are larger "umbrella" studies. 
- [ ] The counts for studies/consortia also needs to be accurate instead of double-counting. 7 consortia and 21 studies is not accurate.
- [ ] There also needs to be a tooltip or other guidance defining what "studies" and "consortia" are since these seem to be defined by our team. Pulling the definitions from the schema would be fine. 
2. The nesting information needs to be improved on the main data portal page. 
- [ ] The "omics data coming soon" needs to be removed from the umbrella study, particularly if processed data exists for the child studies. Screenshot is here: 
<img width="1425" alt="Screenshot 2024-02-21 at 6 29 24 AM" src="https://github.com/microbiomedata/nmdc-server/assets/76500011/86e6fbb9-78d4-4fce-8ee3-120661a31c2c">
- [ ] Different icons should be used to represent the umbrella studies and individual studies. This could help with the above for how to differentiate the two instead of having a split-plane representation.
- [ ] As Alicia mentioned, WHONDRS is part of GROW.
3. The consortia landing pages need a lot more detail/information pulled from the individual studies. Maybe this is already in the works, but below is a screenshot of what I would like to see: 
<img width="1710" alt="Screenshot 2024-02-21 at 6 46 47 AM" src="https://github.com/microbiomedata/nmdc-server/assets/76500011/a63089dc-ad3a-49c6-a0b0-d5235c7055c2">
- [ ] it would also be useful to have the DOIs and funding information also on the umbrella page so it's obvious what information is available. I can understand the all the associated links would clutter the page, so those can just be for the individual study pages. 
- [ ] It also looks like the link icons have lost the logos that we originally had (e.g., KBase). I would also like to have the icons for ORCiD and NEON (and others as they are available).

**Comment by mslarae13** [comment]
From Wednesday conversation, from Emiley's response
1. Move consortia above study
2. Add 'i' tool tip for how study is different from consortia
3. @marySalvi note from @aclum , the GROW study name vs title is probably why it's showing up twice

**Comment by lamccue** [comment]
Additional fixes:
- [] Under "Additional Resources" remove the "Data" subsection, that is now largely redundant with the Data DOIs
- [] Move links that are currently under "Data" to the "Links" subsection
- [] Parent Studies should have the normal fields: Title, Description, PI, Team, Funding sources, NMDC Details, Additional Resources (on dev now, they are missing PI, Team, Funding sources)
- [] Consortia pages should have these fields: Title, Description, image of the consortia logo, website link to home for the consortia, Team, Funding sources NMDC Details, Additional Resources
- [] website link to home for the consortia needs a schema change so that this link is stored somewhere that identifies it as this different type of link; this type of link is only expected for consortia

**Comment by mslarae13** [comment]
Last week it was decided to remove the counts on study and consortia

Above listed is the 'roll up' of the children to the parents. Roll up sample counts to parent study / consortia landing page.
Rolling up the -omics counts will affect the search & will not be rolled up.

**Comment by ssarrafan** [comment]
Just when you think it's done.... almost done! Moving to the next sprint.

**Comment by mslarae13** [comment]
@brynnz22  will add WHONDRS logo
@brynnz22  will correct mCAFE and add PI photos
Need to add nmdc:sty-11-hdd4bf83 Andreas Baumler @lamccue 
- Lee Ann will share the image for Brynn to add to change sheet
- - https://health.ucdavis.edu/medmicro/includes/images/faculty/Baumler-bio.jpg

Need to add nmdc:sty-11-t91cwb40 Michelle O'Malley image @lamccue 
- Lee Ann will share the image for Brynn to add to change sheet
- - https://chemengr.ucsb.edu/sites/default/files/styles/people_thumb/public/people/images/michelleomalley.jpg?itok=2gSVqhLX&c=4d01a055c4485c20b5b2ecf0445336f4

**Comment by marySalvi** [comment]
closed with collective efforts from these PRs: #1158 #1161 #1164 #1169 #1181 #1192
