### ISSUE TITLE
Create submission portal landing page

### ISSUE THREAD

**Issue by emileyfadrosh** [microbiomedata/nmdc-server#1144]
An improved landing page for the Submission Portal is needed to help orient users and provide links to the quick start guide, tutorials, and reference materials. A mock up of the landing page is [here](https://docs.google.com/document/d/1IG4xOQDyBobLYDafZm99vhqtNLF739zDBjALTIn3IOA/edit#heading=h.4sa2cvkl28kc) and also a screenshot below. The following links would need to be included: 

1. Quickstart: https://nmdc-documentation.readthedocs.io/en/latest/howto_guides/submit2nmdc.html
2. Tutorial: https://nmdc-documentation.readthedocs.io/en/latest/tutorials/submission_portal.html
3. Reference: https://nmdc-documentation.readthedocs.io/en/latest/reference/metadata/combined_schema_docs.html

![Screenshot 2024-02-20 at 2 44 07 PM](https://github.com/microbiomedata/nmdc-server/assets/76500011/edc5f517-900b-40a5-bd25-88298d0cd4d1)

FYI @mslarae13 @jkelliher-github @shreddd @ssarrafan

**Comment by eecavanna** [comment]
Someone said, during the infrastructure meeting, that this page was proposed so that the web page isn't "blank" when someone has no submissions. That leads me to wonder whether people want this stuff to only appear in that situation (i.e. only appear if the user has no submissions), or to always be visible (regardless of how many submissions the user has).

**Comment by ssarrafan** [comment]
> Someone said, during the infrastructure meeting, that this landing page content was proposed so that the web page isn't "blank" when someone has no submissions. That leads me to wonder whether people want this landing page content to only appear in that situation (i.e. only appear if the user has no submissions), or to always be visible (regardless of how many submissions the user has).

Good question @eecavanna.  What are your thoughts @emileyfadrosh @mslarae13?

**Comment by emileyfadrosh** [comment]
Here are my suggestions: Have the full landing page for new users, but also have a modified banner with the same help links for users who log in and have a submission in the works. Hope this makes sense! 
 
**BEFORE**
![Screenshot 2024-02-22 at 12 59 05 PM](https://github.com/microbiomedata/nmdc-server/assets/76500011/edd0ea3a-0309-4804-b229-96f3a6d84948)
**AFTER**
![Screenshot 2024-02-22 at 3 17 44 PM](https://github.com/microbiomedata/nmdc-server/assets/76500011/26013b0c-76ab-4a71-b8ad-031bfa611b2b)

And for users who have a new submission, there would be a modified guidance to still retain this information but not have a full page: 
**BEFORE**
![Screenshot 2024-02-22 at 12 59 35 PM](https://github.com/microbiomedata/nmdc-server/assets/76500011/e9e814d5-75e4-446d-9d39-d752969a7d2f)
**AFTER**
![Screenshot 2024-02-22 at 3 34 25 PM](https://github.com/microbiomedata/nmdc-server/assets/76500011/8688f6dc-dd8a-42df-8149-d7daa9b33828)

**Comment by eecavanna** [comment]
This comment will contain my notes about implementing this landing page (I'll update the comment as I work on the feature).

### Notes

- Path to source file: `web/src/views/SubmissionPortal/Components/SubmissionList.vue`

**Comment by eecavanna** [comment]
Hi @emileyfadrosh, the mockup on Google Docs contains a few images. Do you know where I might be able to get those images in SVG format; or do you know whether those same images are being used elsewhere on the Data Portal? My goal here is to get SVG (my first choice) or PNG (my second choice) versions of the images.

**Comment by eecavanna** [comment]
**Status update:** A skeleton of the landing page exists in my local environment. Now, it's a matter of adding images and then adjusting the styles/formatting—which I'll do on Friday.

<img src="https://github.com/microbiomedata/nmdc-server/assets/134325062/597bd1de-b6d9-4b8d-9e27-f3b1fb381d6c" width="600" />

**Comment by eecavanna** [comment]
**Update**: In my local development environment, here's the page that a **logged-out user** would see.
   
![image](https://github.com/microbiomedata/nmdc-server/assets/134325062/bcd5c02a-404e-433d-bb53-9a43f349247e)

**Comment by eecavanna** [comment]
**Update:** In my local development environment, here's the page that a logged-in user would see if they have some submissions.

![image](https://github.com/microbiomedata/nmdc-server/assets/134325062/fe124c69-c223-4350-ba38-5bb2bff1b54b)

**Comment by eecavanna** [comment]
**Update:** In my local development environment, here's the page that a logged-in user would see if they do not have any submissions. This page includes the same elements as in the previous screenshot, plus the paragraphs of text.

![image](https://github.com/microbiomedata/nmdc-server/assets/134325062/aaf8a769-44af-4595-afad-e470e0b02052)

**Comment by emileyfadrosh** [comment]
This is looking FANTASTIC!!

**Comment by eecavanna** [comment]
During last Friday's hackathon, the people in the documentation-focused breakout room agreed ("decided") to stop maintaining the copy of the schema documentation (i.e. [this copy](https://nmdc-documentation.readthedocs.io/en/latest/reference/metadata/combined_schema_docs.html)) that exists on the main NMDC documentation site, and instead have the site "**link out**" to the standalone schema documentation site (i.e. [this site](https://microbiomedata.github.io/nmdc-schema/)).

The main NMDC documentation site has been updated accordingly (this is shown in the screenshot below). Now, the sidebar link that used to point to a page on the main NMDC documentation site, points to the standalone schema documentation site (technically, it links to a w3id URL, which redirects to the latter).

![image](https://github.com/microbiomedata/nmdc-server/assets/134325062/16f2de86-57c0-40a9-ba1f-4cee5b4c2b04)

@shreddd and I are writing this ADR (still in a draft state) about that agreement: https://github.com/microbiomedata/issues/blob/0010-doc-building/decisions/0010-documentation-setup.md

@emileyfadrosh, given the above "decision," are you OK with me having the "**Reference**" icon on this landing page link to the standalone schema documentation site (i.e. [this site](https://microbiomedata.github.io/nmdc-schema/)) instead of to the copy of the schema documentation (i.e. [this copy](https://nmdc-documentation.readthedocs.io/en/latest/reference/metadata/combined_schema_docs.html)) that exists on the main NMDC documentation site?

**Comment by ssarrafan** [comment]
Since this issue is about the landing page (and not specifically the docs), can this issue be closed?  @eecavanna @emileyfadrosh

**Comment by eecavanna** [comment]
Hi @ssarrafan, my plan is to make the 1 change `naglepuff` suggested today (regarding the spelling of "ORCiD" versus "ORCID"), then re-request a review from him and `marySalvi`, then merge it in once they approve it. I'm waiting to close this issue until that merge happens.

**Comment by shreddd** [comment]
Thanks - for the logged-out user page, can we make it more obvious that folks need to login to create a submission? Some possibilities (any combination of these based on your judgement)
- Use with some bigger/bloder text to draw attention to login
- Use an icon in the gray section that prompts the user to login to create submission. 
- Replace Gray with a different color or add a border

**Comment by eecavanna** [comment]
Thanks for sharing that feedback, @shreddd. I have created a new issue for it (at: https://github.com/microbiomedata/nmdc-server/issues/1187) and will close this one.
