### ISSUE TITLE
Data portal - KEGG ingest issues from mongo functional_annotation_agg collection

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1145]
I was looking at some of the KEGG results to get ready for the workshop last weekend and there is an issue with ingest from mongo prod to postgres.
 If I look for KEGG.ORTHOLOGY:K00929 in `functional_annotation_agg` with `{"gene_function_id":'KEGG.ORTHOLOGY:K00929'}` I get 807 documents 
If I grep the postgres backup for `K00929` I just get a single record (nmdc:ca1fba4fe247a9c804052c4c44330605	KEGG.ORTHOLOGY:K00929	1	t) that is from the metap_gene_function_aggregation collection

When I look in the data portal with faceted search the results match what is in postgres, just a single sample is returned.
![Screenshot 2024-02-21 at 11 31 35 AM](https://github.com/microbiomedata/nmdc-server/assets/8196591/0d6dc51a-1fef-41f1-a048-3bbe094d8134)

Assigning to @naglepuff since Mary is working on feedback from study page refresh testing.

cc @ssarrafan @shreddd @jeffbaumes

**Comment by aclum** [comment]
Grepping the backups in postgres this stopped working end of January 31 2024
[aclum@dtn01 pgdump]$ grep -c K00929  dump_nmdc-pg_main-prod_nmdc_b_2024-01-30_10-10-03
661
[aclum@dtn01 pgdump]$ grep -c K00929  dump_nmdc-pg_main-prod_nmdc_a_2024-01-31_10-10-02
4

**Comment by aclum** [comment]
this corresponds to [v0.17.0](https://github.com/microbiomedata/nmdc-server/tree/v0.17.0)

**Comment by aclum** [comment]
cc @pkalita-lbl

**Comment by naglepuff** [comment]
@aclum is this the only KEGG term that is affected?

**Comment by naglepuff** [comment]
First thing to try is run ingest. I'll go ahead and do that now.

**Comment by naglepuff** [comment]
> First thing to try is run ingest. I'll go ahead and do that now.

The redis service is down, so I'll hold off on that ingest for a bit. I decided to take a look at the cron job that is now used for ingest. It is invoked with the following command:

```bash
nmdc-server ingest -vv --swap-rancher-secrets
```

The cli command is defined [here](https://github.com/microbiomedata/nmdc-server/blob/0e9fbf2349baaebd447a19aaae09e5226551f484/nmdc_server/cli.py#L61-L66). There is a default value for `function-limit` of `100`.

Since no limit is specified by the cron job, I believe only the first 100 gene annotations for each workflow are being ingested. @pkalita-lbl this would probably explain the difference in time between running via the cron job vs. via the API.

My theory is that updating the cron jobs to:

```bash
nmdc-server ingest -vv --function-limit=0 --swap-rancher-secrets
```
and then re-running will fix the issue.

**Comment by pkalita-lbl** [comment]
Both the dev and prod `portal-ingest` CronJobs on Rancher have been updated to use the `--function-limit=0`, and they both have been manually run. No further work to do here.
