### ISSUE TITLE
Add Runtime API link to "Products" menu (on website)

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1330]
it came up during API user research that there is no link to our API from our main webpage. Please add `NMDC Runtime API` to the Products drop down menu from https://microbiomedata.org/ which would hyperlink to https://api.microbiomedata.org/docs#/

**Comment by naglepuff** [comment]
What's the typical process for updating links in the top bar? I think there are a few places where this would have to get added to keep things consistent across all NMDC sites (pinging @pkalita-lbl because I know he's done updates like this in the past)

I have no issue with implementing this for the data portal, but I've never made any changes to the main site, so I wouldn't necessarily be the best person to update this across the board.

**Comment by aclum** [comment]
Who normally does this? @eecavanna

**Comment by pkalita-lbl** [comment]
Eric or I generally make updates to the header of the WordPress site (although technically anyone with admin access should be capable). There isn't much of a formal process around it beyond someone pinging one of us on Slack 😅. We also tend not to stress out too much about updating the WordPress header first (which take effect immediately) and letting the portal header get back in sync at the next release.

**Comment by eecavanna** [comment]
I can implement this on the website. I have a few question @aclum:

1. Confirming: What do you want the menu item to say (e.g. `NMDC Runtime API` versus `Runtime API`, `Runtime`, `API`, etc.)? Some of the other products have dropped the leading `NMDC ` from their names in the menu.
2. Where in the dropdown menu (i.e. at which position) do you want the menu item to be (e.g. top, bottom, immediately below "NMDC EDGE", etc.)?

I think @jkelliher-github is typically involved in the decisions of adding items to the website menu, so I will tag her here.

Also, I think NMDC EDGE recently started replicating the website's header menu, in which case @yxu-lanl would also be a stakeholder here.@yxu-lanl, I recommend holding off until the website has been updated, as I consider its menu to be the authoritative one.

<img width="1039" alt="image" src="https://github.com/user-attachments/assets/3b4c1cc7-5730-47d4-b2d6-2ec979b78d83">

**Comment by aclum** [comment]
we can drop the leading nmdc so 'Runtime API'. Bottom of the products list is fine with me if it is okay with @jkelliher-github

**Comment by eecavanna** [comment]
Hi @jkelliher-github, are you OK with a "Runtime API" item being added to the website navigation menu?

Here's what it would look like:

![Image](https://github.com/user-attachments/assets/0fe2a1b3-b239-4d16-886a-e48feeca5c20)

On a side note, I am wondering whether labeling it as the "Data API" would be a more approachable name from the perspectives of our typical users.

**Comment by eecavanna** [comment]
Hi @emileyfadrosh, in this ticket, we are discussing the proposal of adding a link to the Runtime API to the "Products" menu on the website<sup>1</sup>.

<sup>1</sup> And to all the "_copies_" of that menu; e.g. the one on the data portal, the one on the submission portal, and the one on NMDC EDGE.

There is a mockup in my previous comment (above).

@ssarrafan suggested I bring this proposal to your attention so you are aware of what is being proposed (thanks, @ssarrafan!). Do you have any concerns about this item being added? We can discuss this on Slack in case you prefer that.

**Comment by emileyfadrosh** [comment]
Thanks @eecavanna @ssarrafan -- can we just simplify it to "API" or "Data API" as you suggest? I wonder if "runtime" would confuse users outside our team. Thanks!

**Comment by eecavanna** [comment]
I'm OK with either of those. Here's what they'd look like:

| Data API | API |
| -- | -- |
| ![Image](https://github.com/user-attachments/assets/5e6b8f72-9947-43f7-b523-37a80a97e821)   | ![Image](https://github.com/user-attachments/assets/dce1c254-554d-4e68-9345-3dbc9f2c6629)   |

I prefer "Data API" (compared to "API" alone). I think it's because it is similar to "Data Portal" (another menu item) and I think the presence of those two items together reinforces the fact that we provide two ways to access the data: a "Portal" tailored for humans and an "API" tailored for computer programs.

**Comment by ssarrafan** [comment]
I like Data API better too

**Comment by eecavanna** [comment]
OK, thanks, everyone. I'll go ahead and add a "Data API" item to the website menu now.

**Comment by eecavanna** [comment]
The link is now live on the website.

![Image](https://github.com/user-attachments/assets/d5b81f56-94c5-4684-9b88-0a0faf4d782b)

I'll create separate tickets in `nmdc-server` and `nmdc-edge` about updating those "instances" of the menu accordingly.

**Comment by eecavanna** [comment]
OK—I finished creating those more narrowly-scoped tickets. I will close this ticket now.

**Comment by aclum** [comment]
Confirmed I can see this on the main website and the data portal.
