### ISSUE TITLE
Data Portal - backend support GO facet search via mappings - Pfam

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1388]
Search for a GO term in the data portal should use a mapping file to check mapping files since the GO terms aren't stored directly in the data files.

The Pfam -> GO mapping file is https://current.geneontology.org/ontology/external2go/pfam2go

The code should be able to handle multiple mapping files, there will be a related ticket for the KEGG to GO mapping file.

**Comment by ssarrafan** [comment]
@naglepuff This doesn't appear to be active. Can I move this to the next sprint or backlog @aclum ?

**Comment by aclum** [comment]
looping in @sierra-moxon

**Comment by sierra-moxon** [comment]
https://purl.obolibrary.org/obo/go/go-basic.json <-- this should have the terms, definitions, etc needed for our use cases. 
https://geneontology.org/docs/download-ontology/ defines the 'go-basic' file contents.  The PURL above is for the JSON representation of the `go-basic` content. 

(As an aside, I'm working on a generic ontology loader that will take ontology files and move them into MongoDB so that term names, descriptions, cross references, and synonym metadata will be available for ontologies like GO, ENVO, and ChEBI directly.  here it is - https://github.com/sierra-moxon/ontology_loader.  It's just in my own org for ease of dev, but happy to move/demo/etc when it's far enough along).

**Comment by ssarrafan** [comment]
@aclum @naglepuff moving to next sprint but please let me know if you can't work it on in the next 2 weeks.

**Comment by ssarrafan** [comment]
Assuming this is still Mike's next priority?  @naglepuff @aclum let me know if this should be in the backlog instead

**Comment by aclum** [comment]
Yes, this is the next priority.  It is related to milestone 2.12.2 which is due this quarter (end of Dec) so we need to work on this so it can be part of the December release.
