### ISSUE TITLE
FacetChart removes query conditions on omics_type

### ISSUE THREAD

**Issue by jbeezley** [microbiomedata/nmdc-server#159]
I don't know if this is intentional or not, but it seems counter-intuitive that when you filter on a specific omics_type, the bar chart shows results containing other types.

E.g.

http://lb.nmdc-dev.development.svc.spin.nersc.org/type/project/search?c%5B0%5D%5Btable%5D=project&c%5B0%5D%5Bfield%5D=omics_type&c%5B0%5D%5Bop%5D=%3D%3D&c%5B0%5D%5Bvalue%5D=Lipidomics

**Comment by jeffbaumes** [comment]
The chart is supposed to show grey bars for unselected data, and show the selected counts instead of the total. The environments bar chart does this (see below for example) but it looks like this one doesn't. @subdavis could you investigate?

http://lb.nmdc-dev.development.svc.spin.nersc.org/type/biosample/search?c%5B0%5D%5Bfield%5D=omics_type&c%5B0%5D%5Bop%5D=%3D%3D&c%5B0%5D%5Bvalue%5D=Proteomics&c%5B0%5D%5Btable%5D=project&c%5B1%5D%5Bfield%5D=omics_type&c%5B1%5D%5Bop%5D=%3D%3D&c%5B1%5D%5Bvalue%5D=Metagenome&c%5B1%5D%5Btable%5D=project&c%5B2%5D%5Btable%5D=project&c%5B2%5D%5Bfield%5D=omics_type&c%5B2%5D%5Bop%5D=%3D%3D&c%5B2%5D%5Bvalue%5D=Lipidomics

**Comment by jeffbaumes** [comment]
Ah, yep, makes sense, thanks for fixing.
