### ISSUE TITLE
Remove lipidomics from bar chart

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#241]
Since it's being removed from the sample search results, probably makes sense to remove lipidomics from the bar chart as well.

**Comment by subdavis** [comment]
Should we check on that?  We want to hide the download tab because there's nothing useful to download.

The search allows people to find samples where lipidomics has been run at all, which seems different to me.

Removing it is no problem, but everything we remove like that makes the UI less visually interesting.

**Comment by jeffbaumes** [comment]
Just seems surprising to click on lipidomics and not see any lipidomics in the search results. I expect both this change and the change in the search results will get backed out in the future.

**Comment by jeffbaumes** [comment]
This could wait until Thursday's meeting to discuss.

**Comment by dehays** [comment]
I am not seeing issues for removing "Lipidomics" from other pages (studies, etc.). Is that on your radar or should I add new issues?

**Comment by subdavis** [comment]
All references to Lipidomics are being scrubbed.

**Comment by dehays** [comment]
Thanks @subdavis
