### ISSUE TITLE
Do the values in this study list look correct?

### ISSUE THREAD

**Issue by subdavis** [microbiomedata/nmdc-server#253]
![Screenshot from 2021-02-11 15-49-13](https://user-images.githubusercontent.com/4214172/107697065-bf896b80-6c80-11eb-91de-5f3df54cf2c9.png)

**Comment by jeffbaumes** [comment]
@dehays could you verify that these new numbers make reasonable sense?

**Comment by dehays** [comment]
I think that the metagenome annotations are double represented.  This is the Stegen study for which JGI sequenced 50 metagenomes (and 0 metatranscriptomes).  So the assemblies and readQC and metaG annotations would be 50:50:50.  (It is possible that we have both the old and the new (IMG) annotations activities.). MAGs at 50, also expected.  I'll look into why there are twice the expected number of annotation activities here.

Also - looks like there is one missing metaP.  We should have 33 rather than 32.  I think there was some delay in getting the 33rd metaP analysis so I will check to see where we lost it.

**Comment by subdavis** [comment]
Lots of conversation about this resulting in changes to the way we compute counts.
