### ISSUE TITLE
Navigation between sections is difficult/confusing

### ISSUE THREAD

**Issue by kfagnan** [microbiomedata/nmdc-server#263]
This may already be a known issue or duplicate. 

Feedback:
"when select "Gene function" the top L menu area disappears. ALso happens on PI pages, so hard to figure out how to get back."

**Comment by subdavis** [comment]
The other parts of the application are essentially not supposed to be part of the current app.

The gene function search page replaces them, based on the feedback that searching between tabs and having to change tabs to get to filter conditions is too confusing.

The search conditions between the old pages and the new gene search page are not related, which is also confusing.

Should we disable all other pages and remove the buttons that link to them?

**Comment by jeffbaumes** [comment]
In one way or another, we should "fix the Frankenstein".

1. I think in order to fully realize the new UI, we need to change the main buttons from the main page to link to the new search page with different visualizations visible so they are "focused" on environments, omics types, gene function. The idea is to have all important search facets visible at all times in the sidebar, and all visualizations available, so the chips become irrelevant.

2. If we really like those other pages for now, the other option is to keep them and add the chips back to the function search page. It is a bit regressive and adds some confusion to the UI but could be the right thing if we don't want to drop those pages yet.

@kfagnan how would you like to proceed for GSP?

**Comment by subdavis** [comment]
@kfagnan https://data.microbiomedata.org has been updated in accordance with #1, which I think provides a more concise and user friendly experience.  We aren't tied to this, just wanted to provide something concrete to demonstrate the idea.

Most relevant are the new tabs at the top of the page and the info buttons that link to the individual results pages.
