### ISSUE TITLE
Study page buttons

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#290]
These buttons on the Stegen study page are clickable but don't do anything. Not sure what the original intention was?
![image](https://user-images.githubusercontent.com/7374085/108245263-ecb49e80-7104-11eb-85f8-50d5b3bbfe52.png)

The numbers on the study page also don't seem to quite match up with what's in the search results:
![image](https://user-images.githubusercontent.com/7374085/108246156-f559a480-7105-11eb-8b3e-0fd4da1a42c1.png)

**Comment by subdavis** [comment]
Buttons are a known issue mentioned in #284, just wanted to get something up quick to help with #263 discussion.

Second issue may require @jbeezley to comment.

**Comment by pvangay** [comment]
@subdavis Thanks. Second issue - I meant that the number of each omic type seems off (i.e. 42 metabolomics on the study page versus 34 metabolomics from the results page).

Also, the Wrighton study page shows that it has proteomic data when I'm pretty sure that dataset only has metaG
![Uploading image.png…]()

**Comment by pvangay** [comment]
@subdavis Thanks. Second issue - I meant that the number of each omic type seems off (i.e. 42 metabolomics on the study page versus 34 metabolomics from the results page).

Also, the Wrighton study page shows that it has 40 proteomics when I'm pretty sure that dataset should only have metaG

**Comment by jbeezley** [comment]
The backend is counting slightly different things.  The 42 is the number of omics_processings with `omics_type = Metabolomics`.  The 34 are the number of metabolomics analysis workflow executions associated with those omics_processings.  In other words, 8 omics_processings have no associated metabolomics analysis workflow executions.  These are:
```
emsl:499399
emsl:499400
emsl:499433
emsl:499449
emsl:499610
emsl:499615
emsl:499616
emsl:499626
```

@dehays Is this an error in the data?  If not, which of the two numbers would you expect to see on the UI?

**Comment by dehays** [comment]
@pvangay As @jbeezley pointed out - you are comparing EMSL instrument / JGI sequencer runs with analysis workflow executions which don't necessarily need to match up BUT when they do not it is very suspicious.  Given the Stegen example above - I'd say it is strange beyond metabolomics (42 instrument runs vs 34 analysis execution) - JGI did sequencing for 50 metagenomes which aligns with 50 Read QC, Read-based taxonomy, assemblies, and MAGs.  But why would there only be 35 metaG annotation workflow activities.  I'd expect 50 metaG annotations.  Big mismatch on NOM 1111 instrument runs vs 230 analysis activities.  (@subdavis The Study info page still displays "Organic Matter Characterization" rather than "Natural Organic Matter")

I'll step back and see look at JSON in the Mongo instance that ingest pulls from and then at the JSON supplied from A2. Feels like for metaG annotation and metaB analysis there are analysis activity docs missing.  For NOM, my first guess based on the numbers is that we still have a bunch of extraneous Stegen instrument runs included beyond those for which analysis was performed.

**Comment by dehays** [comment]
Ok - what I see in Mongo is that the number of metaG annotations displayed does not match what I see in Mongo, but the metaB analysis does. 

@jbeezley for Stegen metaG annotations - I would expect to see 50 based on what I see in Mongo. Reloading your Postgres tables from dwinston_share.metagenome_annotation_activity_set should fix that.

I will investigate why we only have 34 metaB analysis metadata docs for Stegen rather than the expected 42 (Why do we not have analysis for all 42 metaB instrument runs.)

```
>>> stegen_metag_projects_docs = list(db.omics_processing_set.find({"part_of": ["gold:Gs0114663"], "omics_type":"Metagenome"}, ["id", "has_input", "has_output", "omics_type"]))
>>> len(stegen_metag_projects_docs)
50
>>> stegen_metaB_projects_docs = list(db.omics_processing_set.find({"part_of": ["gold:Gs0114663"], "omics_type":"Metabolomics"}, ["id", "has_input", "has_output", "omics_type"]))
>>> len(stegen_metaB_projects_docs)
42
>>> stegen_metaG_project_ids = [d["id"] for d in stegen_metag_projects_docs]
>>> stegen_metaG_project_ids
['gold:Gp0115663', 'gold:Gp0115664', 'gold:Gp0115665', 'gold:Gp0115666', 'gold:Gp0115667', 'gold:Gp0115668', 'gold:Gp0115669', 'gold:Gp0115670', 'gold:Gp0115671', 'gold:Gp0115672', 'gold:Gp0115673', 'gold:Gp0115674', 'gold:Gp0115675', 'gold:Gp0115676', 'gold:Gp0115677', 'gold:Gp0115678', 'gold:Gp0115679', 'gold:Gp0127623', 'gold:Gp0127624', 'gold:Gp0127625', 'gold:Gp0127626', 'gold:Gp0127627', 'gold:Gp0127628', 'gold:Gp0127629', 'gold:Gp0127630', 'gold:Gp0127631', 'gold:Gp0127632', 'gold:Gp0127633', 'gold:Gp0127634', 'gold:Gp0127635', 'gold:Gp0127636', 'gold:Gp0127637', 'gold:Gp0127638', 'gold:Gp0127639', 'gold:Gp0127640', 'gold:Gp0127641', 'gold:Gp0127642', 'gold:Gp0127643', 'gold:Gp0127644', 'gold:Gp0127645', 'gold:Gp0127646', 'gold:Gp0127647', 'gold:Gp0127648', 'gold:Gp0127649', 'gold:Gp0127651', 'gold:Gp0127652', 'gold:Gp0127653', 'gold:Gp0127654', 'gold:Gp0127655', 'gold:Gp0127656']
>>> len(stegen_metaG_project_ids)
50
>>> stegen_metaB_project_ids = [d["id"] for d in stegen_metaB_projects_docs]
>>> len(stegen_metaB_project_ids)
42

>>> stegen_mg_annotations = list(db.metagenome_annotation_activity_set.find({"was_informed_by": {"$in": stegen_metaG_project_ids}}))
>>> len(stegen_mg_annotations)
50
```

**Comment by dehays** [comment]
All of Yuri's Stegen metaB analysis docs are in Mongo.  But when looking at metaB instrument runs for Stegen - there are 34 with sample input and 8 without.  

`{"part_of": ["gold:Gs0114663"], "omics_type":"Metabolomics", "has_input":null}`
FYI pymongo doesn't like that filter due to the null.  But MongoDB Compass has no problem with it.

Bottom line - I think we have a much larger set of omics_processing for metaB, NOM and metaP than we do metaB analysis, NOM analysis and metaP analysis.  Those EMSL datasets used as input for analysis workflows may be consistent with those EMSL datasets for which input samples have been identified (at least in the metaB case).  I'll look at NOM and metaP and at those related to the Brodie study - I expect that a number of omics_processing (those without known inputs) can be removed. I'll check to see if any cases exist where analysis was done omics_processing that lacked input samples.
