### ISSUE TITLE
Need a useful page when NERSC is unavailable

### ISSUE THREAD

**Issue by kfagnan** [microbiomedata/nmdc-server#385]
I'm not sure this is the best place for this issue. https://data.microbiomedata.org should have a useful redirect when NERSC resources are unavailable. 
<img width="1350" alt="Screen Shot 2021-05-17 at 5 28 51 PM" src="https://user-images.githubusercontent.com/1504015/118572607-b43d5480-b735-11eb-8d3b-bef6e3faf19c.png">

**Comment by subdavis** [comment]
I understand that CloudFlare was suggested for this.

Cloudflare is a DNS soltuion to this problem that would need to be implemented by the operators of the domain.  It would require a bit of planning because as the nameserver changes propagate, you'd want cloudflare pre-configured to serve the same information as is currently coming from the registrar.

You'd also need to choose to have Cloudflare own all records on microbiomedata.org or just data.microbiomedata.org, in which case the dev domain would need to be `dev.data.microbiomedata.org` instead of `data.dev.microbiomedata.org` so that the dev domain fell under cloudflare's jurisdiction.

I can guide on this, but I don't think Kitware should own the cloudflare account, since that would be a bit like Kitware controlling microbiomedata.org.

A good first pass would simply be to enable Cloudflare's "Always online" feature which would show a banner on the page when it was down: https://support.cloudflare.com/hc/en-us/articles/200168436-Understanding-Cloudflare-Always-Online

In this first pass approach, I don't think any action is needed by our team.

**Comment by dwinston** [comment]
Cloudflare site accounts have a "super administrator" role, which should be a stable NMDC email address.[^1] Then, separate administrator accounts can be created for e.g. @kitware.com emails.

[^1]: e.g. `admin@microbiomedata.org`. @kfagnan I see from https://iprequest.lbl.gov/ that you are a contact for microbiomedata.org's DNS MX records -- could you set up forwarding for a dedicated `@microbiomedata.org` email?

**Comment by ssarrafan** [comment]
> Cloudflare site accounts have a "super administrator" role, which should be a stable NMDC email address.[^1] Then, separate administrator accounts can be created for e.g. @kitware.com emails.
> 
> [^1]: e.g. `admin@microbiomedata.org`. @kfagnan I see from https://iprequest.lbl.gov/ that you are a contact for microbiomedata.org's DNS MX records -- could you set up forwarding for a dedicated `@microbiomedata.org` email?

Hi @dwinston. Do you see any other contacts besides Kjiersten?  She out till August and unreachable.  

I will remove @subdavis from this issue for now and add Donny and myself.

**Comment by ssarrafan** [comment]
I believe @dehays is looking into Cloudflare.  I'm moving this to August.

**Comment by ssarrafan** [comment]
@dehays any update on this?  Can I help move this along?

**Comment by dehays** [comment]
Met with Jay Krous and Georg Rath.  data.microbiomedata.org will be included with the websites under the LBL Cloudflare account.  A generic failover page will be added (nothing NMDC specific) so that the user sees a page like "The service you are trying to reach is not available." rather than getting a 503 response.

Closing this issue.  Can create a new issue of additional requirements are needed.
