### ISSUE TITLE
NMDC portal test instance

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#433]
Set up test environment for NMDC portal so changes can be tested and not pushed to production without review/QA

**Comment by jbeezley** [comment]
There are actually two instances of the portal running.

http://lb.nmdc.production.svc.spin.nersc.org/
http://lb.nmdc-dev.development.svc.spin.nersc.org/

The domain currently points at the second (development) URL.  We should move the domain to the second URL, which is only updated manually.

**Comment by subdavis** [comment]
We will need to discuss how to make changes in our workflow to address this.

For example, should we have a new "stage" branch that goes to the QA environment, and then merge to main in more batched releases at the end of the sprint?

**Comment by ssarrafan** [comment]
> We will need to discuss how to make changes in our workflow to address this.
> 
> For example, should we have a new "stage" branch that goes to the QA environment, and then merge to main in more batched releases at the end of the sprint?

Good to hear there are already 2 instances.  @subdavis I hope it's ok to assign this to you.  Let me know if you'd like to discuss it at this week's meeting or if the discussion needs to happen just on the Kitware side.

**Comment by dehays** [comment]
@subdavis Yes, the straight forward approach I think is what you suggest:  a 'stage' or 'dev' branch that is the branch deployed to  the http://lb.nmdc-dev.development.svc.spin.nersc.org/ instance.

Then for production release, merge tested / blessed stage to main. Tag it with a release version and use main to update http://lb.nmdc.production.svc.spin.nersc.org/

Once what is running on http://lb.nmdc.production.svc.spin.nersc.org/ is what we want.  I should change DNS so that https://data.microbiomedata.org/ goes to https://data.microbiomedata.org/ instead of to http://lb.nmdc-dev.development.svc.spin.nersc.org/ as it does now.

**Comment by dehays** [comment]
Per discussion - I will request data.dev.microbiome.org and have it initially point to http://lb.nmdc.production.svc.spin.nersc.org/

Once http://lb.nmdc.production.svc.spin.nersc.org/ has been tested and is what we want - I can switch data.microbiome.org and data.dev.microbiome.org

**Comment by subdavis** [comment]
This is nearly complete, and is blocked on getting an SSL certificate for data.dev.microbiome.org

**Comment by ssarrafan** [comment]
Moving to "in progress".  @scanon can you help with the SSL cert?

**Comment by subdavis** [comment]
This has been done.
