### ISSUE TITLE
Bottom of popout is unreachable

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#44]
I see the following when selecting a field near the bottom of the page

![image](https://user-images.githubusercontent.com/81305/87943083-87fc6d00-ca6b-11ea-8ce2-bbe05a2a3f82.png)

I cannot scroll to see lower in the popout. If I deselect then reselect the same field, it will appear fully on-screen as expected.

**Comment by subdavis** [comment]
Yeah, I'm aware of this.  It happens because the content isn't loaded until after the v-menu is opened, so the menu doesn't know how large it will be.

To prefetch, you'd have to make an API call for each facet to the API every time the query changed, which 

I think the solution is just to give them all a fixed height.  This will mess up the "description" type boxes where you have paragraphs of text, but those fields are useless anyway since they'll only ever match one thing.

**Comment by jeffbaumes** [comment]
+1 to fixed height. Could you just have text remain 1 line and ellipsis for overflow so that the full paginated table always fits?

**Comment by subdavis** [comment]
Yes.
