### ISSUE TITLE
Facet tooltips

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#505]
Pull the description of fields from the schema and display them in the UI. A simple approach would be to just display on hover like the following:

![image](https://user-images.githubusercontent.com/81305/132861686-0799744f-405b-4f11-858f-9f5582f11f98.png)

**Comment by subdavis** [comment]
I'm not totally sure if tooltips are the best approach here.  It looks fine when you have a 5 word description, but most of the terms here will need more words to provide a useful explanation.  I've traditionally used tooltips as text over icon-only buttons.

For these descriptions, I think it might be better to put them in the dialog that appears after you click the facet.  That's a lot of additional context that sort of works together because you see the facet title, description, examples values, and the type of input that the facet is (number, s electable boxes, tree, etc) all together.

**Comment by jeffbaumes** [comment]
Good point. Feel free to do what makes the most sense. If we want to make it more obvious with less clicking but not make large hovers always appear, we could add small question icons just to the right of every facet name and make the user hover over that. @emileyfadrosh any suggestions here?

**Comment by emileyfadrosh** [comment]
Yes, agree with what makes the most sense. Also, we have been working on putting together a user guide [(),](https://docs.google.com/document/d/1ZrQlhvPLg0Unnce-eKG2eew2r2ezY6NH7_XooMsctCM/edit#heading=h.kj1ew0ng77vl) which could also serve the purpose of addressing navigation questions. @jeffbaumes @subdavis how would you like to have this included on the portal? We should have this done by mid-next week. Thanks!

**Comment by subdavis** [comment]
@dehays reading from https://github.com/microbiomedata/nmdc-schema/blob/main/jsonschema/nmdc.schema.json
