### ISSUE TITLE
Explicit units in data object

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#552]
Make sure that units are explicit in the data object (i.e. Depth search is in cm, but this field is stored in meters so the search doesn't work correctly). This may be related to [the depth range issue.](https://github.com/microbiomedata/nmdc-metadata/issues/355)

From #448

**Comment by ssarrafan** [comment]
Brandon, please add T-Shirt size and any questions. Team is trying to get an idea of the time/effort to do this.

**Comment by subdavis** [comment]
Where are units documented?

I see the info here, but this information isn't really programattically accessible. We are currently keeping our own record of units because the information didn't exist elsewhere, so we can just change the unit to meters short term.

Longer term, we probably want to consume this somehow.

**Comment by ssarrafan** [comment]
@wdduncan and @dehays can you help answer Brandon's question about units?
