### ISSUE TITLE
Portal testing feedback- dev

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#572]
GH issue to document and track bugs and issues reported in dev for January release

**Comment by scanon** [comment]
The items I know of are:
* Some data objects show up in the wrong section.  We think this is a UI issue and not a data issue.  @subdavis is investigating
* KEGG search isn't showing any thing for the new metaG.  I'm working on this now.  It may take another day to finish the mongo updates.

**Comment by subdavis** [comment]
@scanon @dehays Dev has been updated for the #570 issue.  Please verify you now see what is expected.

https://data.dev.microbiomedata.org/?q=ChgIABABGAMiECJnb2xkOkdzMDEwMzU3MyIKFAgAEAIYAiIMIk1ldGFnZW5vbWUi

**Comment by scanon** [comment]
@subdavis Looks good to me.

**Comment by emileyfadrosh** [comment]
@subdavis I think there is still perhaps (?) an issue with the publication DOIs not resolving for the Bio-Scales project. Please see this screenshot where the "Other Publications" DOI is listed as "(2020). Office of Scientific and Technical Information (OSTI). https://doi.org/10.46936/10.25585/60000017" -- this should probably be removed entirely since the dataset DOI above is the same. Thanks! 
<img width="1648" alt="Screen Shot 2022-01-21 at 2 33 34 PM" src="https://user-images.githubusercontent.com/76500011/150610328-88306849-cef7-463a-9825-923f01de09d8.png">

**Comment by subdavis** [comment]
@emileyfadrosh the reason for this is that the DOI associated with Bio-Scales is not a "dataset" type DOI according to https://doi.org/api/handles/10.46936/10.25585/60000017

It is a "grant" type.

The "Dataset Citation" section in the UI shows citations for "dataset" types, and everything else is listed in "other publications".  So it's actually the same citation listed twice because at some point in the past we worked around this by hard-coding the text of the dataset citation.  Then you get the duplicate.

This doesn't seem like something to handle on the portal side.  Should there be a dataset citation associated with this dataset independent of the grant? 

Because we are using a DOI lookup service to get the information about "other publications", the schema needs to have some way of indicating that a given DOI should be treated as a dataset even if it's not one.

Here's the raw content of the lookup for that DOI:

```
{
  "responseCode": 1,
  "handle": "10.46936/10.25585/60000017",
  "values": [
    {
      "index": 1,
      "type": "URL",
      "data": {
        "format": "string",
        "value": "https://www.osti.gov/award-doi-service/biblio/10.46936/10.25585/60000017"
      },
      "ttl": 86400,
      "timestamp": "2021-07-01T23:26:04Z"
    },
    {
      "index": 700050,
      "type": "700050",
      "data": {
        "format": "string",
        "value": "1633707519"
      },
      "ttl": 86400,
      "timestamp": "2021-10-08T16:33:48Z"
    },
    {
      "index": 100,
      "type": "HS_ADMIN",
      "data": {
        "format": "admin",
        "value": {
          "handle": "0.na/10.46936",
          "index": 200,
          "permissions": "111111110010"
        }
      },
      "ttl": 86400,
      "timestamp": "2021-07-01T23:26:04Z"
    }
  ]
}
```

**Comment by dehays** [comment]
@emileyfadrosh We should address this in the schema and metadata.  The issue is that records associated with DOIs can be one of several types.  The schema can help specify types (dataset, publication, award). For example, a study could have attributes that take list values for 'dataset_doi_list', 'award_doi_list', 'publication_doi_list'. The client could then use the attribute to determine how to handle the values in each list.

For the DOI being discussed here - the correct information is the OSTI reference as that is the record associated with the DOI.  (The hardcoded part above in the 'Dataset Citation' group is not actually accurate because that DOI is not associated with a dataset.)

**Comment by ssarrafan** [comment]
Closing this, portal updated and release done.
