### ISSUE TITLE
"select all" feature to allow users to replace contents of the DH interface

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#670]
Look into this to assess feasibility

**Comment by ssarrafan** [comment]
@subdavis Today is mid-sprint so I’m checking in to see how you’re doing with your assigned GitHub issues.  Please update this issue and let me know if you’re still actively working on it and it’s on track for finishing by the end of June. If you’re not working on it due to other priorities let me know if you plan to work on it in July or if it should be moved to the backlog for reprioritization.

**Comment by ssarrafan** [comment]
@jeffbaumes @subdavis @mcovalt this is an old issue.  I will re-assign to Matt but let me know if it's not on your list for this month.

**Comment by ssarrafan** [comment]
@jeffbaumes I'll remove from sprint and add the "backlog" label.

**Comment by ssarrafan** [comment]
Closing this issue. It's over a year old. No updates. @mslarae13 @aclum

**Comment by mslarae13** [comment]
I don't even recall what this was for..
