### ISSUE TITLE
Add creator, creation date to admin page

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#673]

**Comment by ssarrafan** [comment]
@jeffbaumes is this slated to be worked on in May?

**Comment by ssarrafan** [comment]
@subdavis Today is mid-sprint so I’m checking in to see how you’re doing with your assigned GitHub issues.  Please update this issue and let me know if you’re still actively working on it and it’s on track for finishing by the end of June. If you’re not working on it due to other priorities let me know if you plan to work on it in July or if it should be moved to the backlog for reprioritization.

**Comment by subdavis** [comment]
This is on track to be completed in June sprint.
