### ISSUE TITLE
GSP Feedback: Data Portal: Collection Date Slider

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#675]
Users reported that it's 

1. unclear what data this visual represents (user need: medium. suggestion: add a legend or title "Sample Collection Date")
2. that it's difficult to use the slider when selecting exact dates (user need: low if https://github.com/microbiomedata/nmdc-server/issues/674 is implemented)

**Comment by ssarrafan** [comment]
Assigning to data portal GLADOS sprint per meeting 9/22/22.

**Comment by pvangay** [comment]
This issue is actually two tasks:
1. Adding a title to this visualization to "Collection Date"
2. Implementing @jeffbaumes's proposal of overlaying a box over the histogram as a way to select dates - replacing the current slider mechanism. This box can be moved along the x-axis (and lengthened/shortened) as needed. The granularity will be coarser - this is okay because users can select and enter in more precise dates using the collection date search facet on the left hand side. 

Kitware will prototype something to share with the team.

**Comment by ssarrafan** [comment]
Met with @jeffbaumes and this issue is almost complete but will leave open to demo at the infrastructure sync meeting Thursday before closing out. Moving to the next sprint.

**Comment by naglepuff** [comment]
Part of this change included removing outdated text and adding new text into the box that appears when you hover over the question mark icon in the card with the date histogram. 

Old text:
![date_hist_old](https://user-images.githubusercontent.com/7085625/194415764-d72edc22-e958-48d4-a76a-d2125c807b07.png)

New text:
![date_hist_new](https://user-images.githubusercontent.com/7085625/194416585-fbd1dd59-f00d-4a1d-b207-d981974cbd57.png)

More specific information "collection date" is found in the sidebar by selecting the "collection date" criterion.
![collection_date_expl](https://user-images.githubusercontent.com/7085625/194417840-f4a09b20-ae76-425d-bd0e-6798e628310d.png)

**Comment by mslarae13** [comment]
@naglepuff  looks great!
