### ISSUE TITLE
GSP Feedback: Data Portal: Geographic Location Name

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#676]
Users requested to search geographic location name with more resolution than the state name (e.g. City)

User need: Low
Feasibility: Unknown, Unclear if metadata supports this. Next Steps: @turbomam to check if this is feasible.

**Comment by mslarae13** [comment]
misunderstood the issue here. this isn't a schema or submission portal update. removing from subport squad.

**Comment by aclum** [comment]
Users can search by whatever string is in the value of the geo_loc_name slot. Values may or may not have a city. Sometimes this is the name of the research site instead of a city name. Some values in the database only have a country: state, those would not return anything based on lat/long coordinates b/c this field is a text match on geo_loc_name.
