### ISSUE TITLE
Add Token Authentication

### ISSUE THREAD

**Issue by subdavis** [microbiomedata/nmdc-server#690]
For methods that require authentication, we need another way for consumers of the system to authenticate without a browser.  Users should be able to fetch an API token from the browser that they can use from CURL or python.

## Requirements

* A tokens model associated with a user (many to one)
* CRUD operations on tokens.
* A way to get a token from the web client.
* Handling for token authentication from endpoints that require login.

## TODO

fill in the details.

**Comment by DeepikaGhodki** [comment]
A possible approach: using basic authentication where the users can encode their credentials in a predefined format (name:orcid).  This value would be expected in every request as an Authorization header. The header value is decoded and user details are extracted to validate the user on receiving requests.  But due to lack of security, there may not be much merit in using this.

**Comment by subdavis** [comment]
Unassigning this issue, we're going to wait on setting up token auth until a little later.

**Comment by shreddd** [comment]
Issue #1146 might be a way to address this

**Comment by aclum** [comment]
@shreddd  please comment if this can be closed/depricated in favor of recent auth work by @naglepuff 

cc @ssarrafan

**Comment by ssarrafan** [comment]
Closing this. @shreddd
