### ISSUE TITLE
Submission portal scrolling issue

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#752]
Montana: I can’t scroll to the left again on the submission portal.. I’m in my submission titled “DELETE: Fungal, bacterial, and archaeal communities mediati

**Comment by mslarae13** [comment]
I can’t scroll to the left. I can if I START scrolling right, then switch to left (mac track pad). But I can’t just go left.
 
I use google chrome, version “Version 103.0.5060.114 (Official Build) (x86_64)”

Julia was having a similar issue
Chrome: Version 103.0.5060.53 (Official Build) (x86_64)

**Comment by jeffbaumes** [comment]
I'm guessing this is an unintentional bug introduced while fixing another problem, which was that scrolling left on mac inadvertently caused back navigation in the browser. @mcovalt we may want to back out https://github.com/microbiomedata/nmdc-server/pull/727/files and see if that fixes it, then attempt to re-fix the back navigation issue in a way that doesn't have Montana's effect, since this bug seems worse.

@mslarae13 is this a critical blocker for getting things done at this point? If so we can prioritize.

**Comment by ssarrafan** [comment]
Matt worked on this. Montana checked and it's fixed. Closed.
