### ISSUE TITLE
Disappearing data and submissions in submission portal

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#757]
Two instances of data disappearing for users trying to submit their data to the submission portal.  @mcovalt can you please help investigate this?  Here are the details from Montana:

Holly Andrews (0000-0002-5173-0826)
Submission started, disappeared… started a new one and the metadata didn’t save

Jianqiu Zheng (0000-0002-1609-9004)
Started and completed submission for JGI sample shipment. But the submission is gone. (I wanted to check that she finished the study information & it isn’t there)

@mslarae13 @turbomam

**Comment by mslarae13** [comment]
From Slack 
"
[Jeff Baumes](https://app.slack.com/team/UTE1XFADU)
  Matt Covalt and I just had a discussion about the recent issues with unstable user submission data. My best guess is that the addition of tracking and sorting submissions by user caused something to go wrong here, and I unfortunately don't see a route to recover Jianqiu's data. There are long term and short term things to consider here. Short term we need to fix data integrity issues now so data does not get lost like this again, and the fastest path to more stability is the following, which 
[@Matt Covalt](https://nmdc-group.slack.com/team/U0356KFUAJW)
 will put as highest priority:
Save submission data to the server automatically any time data changes in the UI. Currently it only happens when a user validates the data which is not intuitive.
Regularly backup any data generated by nmdc-server that is not stored elsewhere. This consists of submission data and download count data.
[@Mark Andrew Miller](https://nmdc-group.slack.com/team/U01S4N8NZJT)
 There are also long-term things to consider, the biggest being possibly consolidating all data into a singular backend data store. Currently mongo "owns" data coming from workflows, and nmdc-server postgres "owns" data coming from the UI. Instead of adding a new data flow link from nmdc-server to mongo at this point in time, I'd rather wait until we determine the ultimate data ownership and database model in the renewal. In the architecture's current form, having a new user log in to nmdc-server require a change sheet submission/ingest before a they continue to start a submission or download data is clearly not good UX. For now, nmdc-server needs a lightweight way to register a new user in postgres. We effectively just need to know "Have we seen this orcid before?" "What submissions are associated with the orcid?" and "Is this orcid an admin?". We do not want to keep track of anything beyond is-admin and orcid, which should be easy enough to merge with a Person model at any point. Basically I don't see a bifurcation/merge event, ours is super lightweight, so the risk is low here even if we have the bigger question (unified models in general) to contend with in the months ahead. 
[@Shreyas Cholia](https://nmdc-group.slack.com/team/U035D6QTVP0)
 please advise if you have any other thoughts here.

**Comment by mslarae13** [comment]
Discussed at infrastructure sync 08-04. A back up will start being made before any migration. Likely there were updates that caused loss

**Comment by mslarae13** [comment]
@naglepuff @marySalvi @shreddd @emileyfadrosh @pkalita-lbl @aclum @jeffbaumes 

It looks like this has happened again. Mary is looking into it right now

This submission is missing: https://data.microbiomedata.org/submission/4b07a58a-ef04-48d0-b3cb-9d10b75c1946 

We haven't done a submission portal migration in MONTHS, hopefully there's a backup somewhere??

**Comment by eecavanna** [comment]
Where are the apps and database(s) that make up the submission portal (I think that amounts to: a web client app + a web server app + and a DBMS/database server that is specific to the submission portal) currently hosted; e.g. Spin, AWS, GCP?

**Comment by pkalita-lbl** [comment]
The submission portal front-end and back-end code is part of https://github.com/microbiomedata/nmdc-server. It uses the same Postgres database that the data portal uses to store data. Specifically the submission data is stored in the `submission_metadata` table (with a join on the `user_login` table). I don't know as much about the process that populates the data portal search tables as the Kitware folks, but I know it involves some table truncation. I'm a little scared that the [definition](https://github.com/microbiomedata/nmdc-server/blob/631c823101b904356c7c00922d44fe4ca65b66c7/nmdc_server/database.py#L115-L130) of this `truncate_tables` function doesn't exclude `submission_metadata`.

**Comment by eecavanna** [comment]
>I'm a little scared that the [definition](https://github.com/microbiomedata/nmdc-server/blob/631c823101b904356c7c00922d44fe4ca65b66c7/nmdc_server/database.py#L115-L130) of this truncate_tables function doesn't exclude submission_metadata.

Thanks @pkalita-lbl ! I'm surprised to see that lack-of-exclusion also. Without knowing when that SQL function is used in practice, I am wondering (I think this is also what you're thinking) whether the affected user submitted data via the submission portal, then this SQL function was used (wiping out that recently-submitted data) before the submitted data was moved to whatever the long-term storage place is.

**Comment by pkalita-lbl** [comment]
@jeffbaumes clarified that the truncation of `submission_metadata` and `user_login` is expected behavior and that those tables are copied from the live DB to the ingest DB in a [subsequent step](https://github.com/microbiomedata/nmdc-server/blob/631c823101b904356c7c00922d44fe4ca65b66c7/nmdc_server/jobs.py#L63-L65). We may still want to double check that it's not possible for a submission to be created created after the copy happens but before the ingest DB comes the live DB (if I'm understanding the ingest process correctly) because that could lead to lost data -- although that's not necessarily what happened to the submissions we're talking about here.
