### ISSUE TITLE
Hyperlink in descriptions sometimes broken

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#820]
Issue:
Some of the hyperlinks in the submission portal are broken. Or don't work with the pop up window.
For example, env_broad_scale. Links when you double click on the header don't open.
When you validate and move to "env_broad_scale" the side window has the link, but not the whole link works......  http://purl.obolibrary.org/obo/ENVO_00000428 ... everything after the _ is missing.

Resolution:
All links work everywhere. In the side window and in the pop up
The full link works.

**Comment by ssarrafan** [comment]
@mslarae13 so can this issue be closed?  Did someone fix them or did the issue just resolve on its own?

**Comment by mslarae13** [comment]
@ssarrafan 
Nope, I just made this issue. Still broken, see the images I attached. No hyperlink in the double clicked pop up, and the hyperlink in the right side window you see upon validation, the link is broken.
![Screen Shot 2023-01-04 at 11 43 38 AM](https://user-images.githubusercontent.com/44581429/210636550-2577e414-cb74-4583-b222-5d639c49b726.png)
![Screen Shot 2023-01-04 at 11 43 45 AM](https://user-images.githubusercontent.com/44581429/210636552-90d40846-211d-4028-9e04-6554cb6946aa.png)

**Comment by mslarae13** [comment]
This might be in scope for the SubPort squad, this issue was uncovered during the JGI user meeting I believe.

**Comment by ssarrafan** [comment]
@naglepuff @mslarae13 if this is actively being worked on please let me know or add to current sprint.  Removing from sprint for now with backlog label.

**Comment by naglepuff** [comment]
Looks like there's a bug [here](https://github.com/microbiomedata/nmdc-server/blob/73c4a1057f8fbdcaa3ed51e2b6246c71ed1cd608/web/src/data/utils.ts#L64). Would likely be an easy fix, let me know how to prioritize this.

**Comment by naglepuff** [comment]
> Looks like there's a bug [here](https://github.com/microbiomedata/nmdc-server/blob/73c4a1057f8fbdcaa3ed51e2b6246c71ed1cd608/web/src/data/utils.ts#L64) (the regular expression doesn't allow for urls with underscores). Would likely be an easy fix, let me know how to prioritize this.

The link bug at least explains the issue with the sidebar. It doesn't explain why the urls in the pop-up version aren't getting "urlified." That would require some deeper investigation, but maybe @pkalita-lbl knows better than I regarding that modal window in the data harmonizer.

**Comment by pkalita-lbl** [comment]
Yeah the double-click pop-up functionality comes directly from DataHarmonizer, and it just doesn't implement the functionality of parsing out URLs in the slot descriptions and turning them into clickable links. So that's why you get no link at all in the pop-up. It's not a bad idea, but I'll need to open a ticket on the DataHarmonizer side and propose that change.

**Comment by aclum** [comment]
@pkalita-lbl any update on this on the DH side? Was a ticket filed?

**Comment by pkalita-lbl** [comment]
No I guess I dropped the ball on making the DataHarmonizer issue. But just to be clear DataHarmonizer does not control what is in the the help _sidebar_, which is what you were reporting in #945.

**Comment by pkalita-lbl** [comment]
1. I made an issue in the DataHarmonizer repo that will fix not having any URLs linked in the help _popup_: https://github.com/cidgoh/DataHarmonizer/issues/388. Not sure what the timeline for that will be, but I think it's lower priority for NMDC since most people probably use the help _sidebar_.

2. It seems we have both this issue and #945 about _certain_ URLs not being correctly linked in the help _sidebar_. I don't care which one we keep open to track fixing that, but we probably only need one. I can make the fix, but I don't know what the schedule (if there is one) for deploys to production or sandbox.

**Comment by ssarrafan** [comment]
I'm closing this issue as a duplicate since the two other issues reported cover the issues here. See #945 and [388](https://github.com/cidgoh/DataHarmonizer/issues/388)

**Comment by mslarae13** [comment]
The ENVO links are still broken....
@aclum  , @naglepuff  , @pkalita-lbl 
![Screen Shot 2023-04-13 at 10 06 29 AM](https://user-images.githubusercontent.com/44581429/231834408-39a390b3-9789-4f6d-a24d-da0bc7863a1c.png)

**Comment by naglepuff** [comment]
What environment are you in? This should be fixed in dev.
