### ISSUE TITLE
GOLD classification search filter tree doesn't populate if no other search filters selected 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#926]
On the development data portal the GOLD classification search filter tree does not populate if there are no other search filters. If a study is selected with a checkbox (ie https://data-dev.microbiomedata.org/?q=ChgIABABGAMiECJnb2xkOkdzMDExMDEzOCI=) then the GOLD classification tree does work correctly. 

On the production data portal the search filter tree appears in both cases.
![GOLD classifcation production data portal](https://user-images.githubusercontent.com/8196591/229653588-f89df4a5-e425-4225-8b9d-2ef7912fbbcf.png)
![missing GOLD filter tree dev](https://user-images.githubusercontent.com/8196591/229653594-dccb1423-15db-4218-b3d4-5f22f8170c30.png)

Thanks to Leah for reporting.

**Comment by naglepuff** [comment]
Looks like the problem may lie with the 1000 soils data. The GOLD classification component renders correctly for the other studies, which is why you were getting it to show up when you had a single study selected.

The biosamples in 1000 soils have values for `ecosystem`, `ecosystem_category`, and `ecosystem_type`. Those biosamples are missing `ecosystem_subtype` and `specific_ecosystem`. Other biosamples in mongo have "Unclassified" as the values for those slots if nothing else applies. I believe the 1000 soils biosamples should be updated to include `ecosystem_subtype = "Unclassified"` and `specific_ecosystem = "Unclassified"`, and I'd be happy to discuss further.

**Comment by aclum** [comment]
I've populated 1000 soils biosample records with `ecosystem_subtype` = "Unclassified" and `specific_ecosystem` = "Unclassified". Additionally, I've populated the metabolomics only bioscales samples with 
`ecosystem` `ecosystem_category` `ecosystem_type` `ecosystem_subtype` `specific_ecosystem`
We can check on this tomorrow after the ingest to dev data portal. 




</body>

</html>

**Comment by aclum** [comment]
Im going to close this issue since it resolved for GSP by changesheet updates and open a new related ticket to address the general issue since these slots are not required by the NMDC schema but are required in postgres.
