### ISSUE TITLE
Data portal collection date not filtering when study selected

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#928]
collection date not filtering when a study is selected. This doesn't work on prod or dev. 

GROW for example there was a bug in GOLD so collection date isn't available for any biosamples.

**Comment by aclum** [comment]
@aclum

**Comment by naglepuff** [comment]
Could you give an example of this behavior?

**Comment by ssarrafan** [comment]
<img width="1304" alt="Screen Shot 2023-08-21 at 10 05 59 AM" src="https://github.com/microbiomedata/nmdc-server/assets/79225425/5da5c34d-f93c-489b-9fc5-b72af69f252e">
@naglepuff this is an example of selecting a study but the collection date section doesn't update like the other areas do like the map and the upset plot.

**Comment by aclum** [comment]
Since time of writing Sujay has added collection date for GROW samples. A good example to use is Bioscales, those samples were all collected in 2020 but the bar chart does not change. You can cross reference with the `collection_date` for class `biosample` where `part_of` equals `nmdc:sty-11-r2h77870`
<img width="1322" alt="Screenshot 2023-08-21 at 10 30 16 AM" src="https://github.com/microbiomedata/nmdc-server/assets/8196591/596a2406-decc-4dfb-a3ef-dff5a92da2ae">

https://data.microbiomedata.org/?q=Ch4IABABGAMiFiJubWRjOnN0eS0xMS1yMmg3Nzg3MCI=

**Comment by aclum** [comment]
@marySalvi are you picking this ticket up while Mike is out next week or should we remove this issue from the sprint?

**Comment by jeffbaumes** [comment]
This will need to go to the next sprint as @marySalvi is working to complete a few other sprint tasks and @naglepuff is not back until next week.

**Comment by aclum** [comment]
@marySalvi  were you able to work on this task this sprint or we should move it to the next sprint?

**Comment by naglepuff** [comment]
@aclum I just did my review on the PR and it looks good/is approved, so this issue will be closed as soon as it gets merged.
