### ISSUE TITLE
Download and import of xlsx file bug in sandbox

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#934]
Downloading the metadata template and importing a completed template has a bug.  It won't work until I validate.. but only sometimes. 

In this recording, I had to put something into the template to get it to download. In another test I did I added nothing to the columns and it downloaded after hitting validate.

Only tested in sandbox. Not sure if it's an issue in prod.

https://drive.google.com/file/d/13FgnxIgLDnOTqwFdgpDUOvXsI07idoXk/view?usp=share_link  - see video here

**Comment by ssarrafan** [comment]
@mslarae13 does this need to be fixed in sandbox before your workshop?

**Comment by mslarae13** [comment]
This is fixed on production... still broken on the sandbox. It's not vital.. but would be good.. also the other project types are missing..

See this video for what is still happening: https://drive.google.com/file/d/1WW8zTdprBIVWcBT6ag0EGmyk7AIeAPs5/view?usp=share_link 

@naglepuff is it possible to sync sandbox with prod by GSP?

**Comment by naglepuff** [comment]
Sandbox and prod should be running the same versions already. I switched them both over to 0.9.1 on Friday. I'm confused by your video, since it was recorded late in the day on Friday, so you should have been seeing the new features. In additional to the missing project types in your videos, I don't see the orange (!) indicating you need to validate each tab in the data harmonizer...
![image](https://user-images.githubusercontent.com/7085625/230950673-d167fbc3-931a-43cb-9d9b-727ec7885aa0.png)
This is what I see as of 12:53 EDT on 4/10 (note all of the new project types)

**Comment by mslarae13** [comment]
@pkalita-lbl  I think you solved this?

**Comment by pkalita-lbl** [comment]
Yes, I trust that it is
