### ISSUE TITLE
neon study logo is now on top of PI name instead of to the left of it

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#942]
This is happening in both dev and prod now. As of Wednesday the study logo was showing to the left of the PI name, the same place where profile_image_url (with a pi picture was). for the [NEON study page ](https://data.microbiomedata.org/details/study/nmdc:sty-11-34xj1150) the study logo is above the PI name and the PI name and websites aren't indented as expected.

**expected behavior**
![neon study page 20230405](https://user-images.githubusercontent.com/8196591/230659538-38fe3d43-1d4e-4eae-adbd-e3efe14f346b.png)

**observed behavior**
![neon study page 20230407](https://user-images.githubusercontent.com/8196591/230659519-2725d152-3e5e-4793-b132-ae2ff5bdc05d.png)

**Comment by aclum** [comment]
The issue is specific to the neon study page, GROW and 1000 soils display as expected still.

**Comment by naglepuff** [comment]
What's your browser/OS? Is this how the page appears for you every time you visit, or only from a specific workflow?

**Comment by jeffbaumes** [comment]
I can see this on Chrome by visiting the page by clicking on the study, as well as when I refresh the study page. It does not appear to happen in Firefox. I notice that the image is quite wide (1562px) and Vuetify does for some reason have a "width: 1562px" on a "responsive" helper div for the v-image. Oddly removing this div or changing its width in the browser dev tools does not fix the reflow. Not sure why it's causing a reflow in one browser but not another.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/81305/230664125-4662a787-559c-4553-9aed-a3ad8ff45719.png">

**Comment by naglepuff** [comment]
I can't reproduce in chrome 110.0.5481.177. I'm seeing the same thing you are in dev tools as well

**Comment by naglepuff** [comment]
@jeffbaumes if you go to the parent div (class `v-image`) and add `max-width: 200px`, does that change anything?

**Comment by jeffbaumes** [comment]
No, it does not fix it.

**Comment by jeffbaumes** [comment]
I believe the cause is not the wide image, but the long links without dashes (dashes seem to wrap in both FF and Chrome but slashes seem to be word wraps in FF but not Chrome, see https://github.com/mozilla/chronicle/issues/238). So somehow we need a different overflow or word break behavior resilient to long links without dashes.

**Comment by aclum** [comment]
This is dynamic for me depending on how big I make my window. If i make my window wider it renders as expected. 
chrome version 112.0.5615.49

**Comment by naglepuff** [comment]
![image](https://user-images.githubusercontent.com/7085625/230675255-360cfea6-a93f-4270-9fda-77ec55c192d9.png)

Chrome and firefox side by side. Notice the link right above the "Team" section.

**Comment by aclum** [comment]
Did this get resolved?

**Comment by aclum** [comment]
This should come after the study copy work for the submission portal. I am working on a data portal squad so mostly trying to confirm what is still outstanding.

**Comment by eecavanna** [comment]
> I believe the cause is not the wide image, but the long links without dashes (dashes seem to wrap in both FF and Chrome but slashes seem to be word wraps in FF but not Chrome, see https://github.com/mozilla/chronicle/issues/238). So somehow we need a different overflow or word break behavior resilient to long links without dashes.

One option is to set the `word-break` CSS property on each `<a>` element to `break-all`.

Here's what the web page looks like with the `word-break` CSS property set to `break-all` (on the offending `<a>` element), in Chrome and Firefox, at a viewport width of `1562px` (I chose 1562px because it was mentioned above). I also included screenshots under the current conditions for reference.

Chrome @ 1562px w/ current `word-break` setting (under these conditions, the "PI info" box wraps)

![image](https://github.com/microbiomedata/nmdc-server/assets/134325062/9dd5cc7c-51a0-4918-bb9f-56e166c73ed0)

Chrome @ 1562px w/ `word-break: break-all`

![image](https://github.com/microbiomedata/nmdc-server/assets/134325062/8f75c3c8-646c-4713-a17a-ee48bae8ba17)

Firefox @ 1562px w/ current `word-break` setting

![image](https://github.com/microbiomedata/nmdc-server/assets/134325062/efa2f436-cfd5-4868-84e7-ad43fe8d1366)

Firefox @ 1562px w/ `word-break: break-all`

![image](https://github.com/microbiomedata/nmdc-server/assets/134325062/f5149756-ba91-45c1-9989-a9075bcbaf31)

References:
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_text/Wrapping_breaking_text
- https://developer.mozilla.org/en-US/docs/Web/CSS/word-break: `word-break: break-word;` is deprecated

**Comment by aclum** [comment]
looks good @eecavanna

**Comment by ssarrafan** [comment]
I think @marySalvi is working on this per the infra sync meeting yesterday. Will move to next sprint.

**Comment by ssarrafan** [comment]
@marySalvi are you working on this issue?  @naglepuff is this still on your radar?

**Comment by marySalvi** [comment]
I believe this will and should be handled by the study page refresh. The best way to handle this bug is to work with the layout but that is about to change shortly.

**Comment by ssarrafan** [comment]
Adding backlog label. Oh hold waiting for study page refresh to recheck.  @aclum FYI

**Comment by aclum** [comment]
@marySalvi  this displays correctly unless I make my window very, very small so my suggestion is closing this out. Do you agree?
