### ISSUE TITLE
Option to search by name and description for study in the data portal

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#965]
Search based on and slots  `title` (title is what is displayed in the data portal, not `name`, and `description` for `study_set`

**Comment by naglepuff** [comment]
Is this request for additional filters available in the search sidebar or a way to filter results of a search without having to page through results? I'm interpreting this as the latter but I wanted to clarify.

**Comment by aclum** [comment]
I originally wrote this to request the latter. Is one of these two options easier than the other to implement? We had a few people at the workshop try and type in a study name in the search sidebar

**Comment by aclum** [comment]
Per @naglepuff request splitting these out into separate tickets, one for study and one for biosample. We discussed today at the infrastructure adding a facet for this vs making the search box global. Mike and Jeff will get back to us on how much each solution would take.

**Comment by naglepuff** [comment]
@jeffbaumes and I spent some time yesterday digging into ideas for this problem, and have a possible solution that would be achievable with just backend changes by expanding how we use the primary "Search" bar in the data portal sidebar (the one at the top of the sidebar):
![image](https://github.com/microbiomedata/nmdc-server/assets/7085625/610d595f-8dbe-4702-8ff2-504b920f1233)

Keep in mind that the screenshots are of a crude version of the proposed functionality.

Currently, using this search bar will dynamically show facets for which there is a value that matches the search text, and enable users to add that filter to the current search. For example, if I type "Kat" into the search bar, I can see that I have two matches for the "PI Name" filter:
![image](https://github.com/microbiomedata/nmdc-server/assets/7085625/a4b976c9-20dc-4e6e-be9f-674e7b149fe3)

Due to how this is already implemented in our backend, we can add additional (static and pre-defined) filters that aren't based on matches, but always appear, allowing text search on fields that we choose. For example, in addition to showing matches for the PI Name filter, we can provide an additional option that would do a full, case-insensitive text search on that field:
![image](https://github.com/microbiomedata/nmdc-server/assets/7085625/a937ffce-6891-43a2-920e-2058abcb999e)

Adding this filter would return all studies whose PI name contains the search string:
![image](https://github.com/microbiomedata/nmdc-server/assets/7085625/fde74d04-689a-42d8-b17d-6517a170c0f5)

We can add similar options for study name and description. (And other text fields)

Is this an acceptable workflow to solve this issue? @aclum 

Note that fully supporting all ingested fields will require some changes to custom SQL functions, namely `nmdc_compare`.

I'd estimate that this could probably be done in a sprint cycle granted it was the primary task for that sprint, possibly accompanied by 1-2 small items.

**Comment by aclum** [comment]
Yes, this is acceptable. @naglepuff Are you done with the doi multivalued work so this can be the main issue for the next sprint?

**Comment by naglepuff** [comment]
No, the DOI work is still ongoing

**Comment by aclum** [comment]
Okay @ssarrafan  please schedule this for the sprint starting 9/25

**Comment by aclum** [comment]
Putting in backlog, this will be after collection date and kegg bug tickets.
